name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image with built package
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/sweetnordic/timetracker:latest
    - name: Build & Push the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/sweetnordic/timetracker:$(date +%s) --tag ghcr.io/sweetnordic/timetracker:latest --label "org.opencontainers.image.source=https://github.com/sweetnordic/timetracker" --label "org.opencontainers.image.description=Time Tracker" --pull --no-cache --push
