name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/sweetnordic/timetracker:$(date +%s) --label "org.opencontainers.image.source=https://github.com/sweetnordic/timetracker" --label "org.opencontainers.image.description=Time Tracker"
    - name: Push the Docker image
      run: docker push ghcr.io/sweetnordic/timetracker:$(date +%s)
