name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/sweetnordic/timetracker:$(date +%s) --label "org.opencontainers.image.source=https://github.com/sweetnordic/timetracker" --label "org.opencontainers.image.description=Time Tracker"
